version: '2'
services:
  zookeeper:
    container_name: zookeeper-document
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    container_name: kafka-document
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  db:
    container_name: database-document
    image: postgres:16-alpine
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courseWork
    volumes:
      - /var/lib/postgresql/data

  backend:
    container_name: backend-document
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
      - '5005:5005'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/courseWork
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - kafka

  ui:
    container_name: documents-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '9000:3005'
    depends_on:
      - backend
