server:
  port: 8888

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

cors:
  allow: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

kafka:
  topics:
    inbox: "inbox-mes"
    outbox: "outbox-mes"